### ISSUE TITLE
Installing One Cache Instance Overwrites Other Servers In Twemproxy

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#187]
On an already configured Gluu Server cluster, if you add another instance of Gluu Server that doesn't have cache installed, you're given the prompt to `Install Cache` on that server exclusively. This doesn't take into account the other servers in the cluster and leaves itself as the only server in the nutcracker/twemproxy configuration. See below:

```
root@c4:~# cat /etc/nutcracker/nutcracker.yml
alpha:
  listen: 127.0.0.1:2222
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  server_retry_timeout: 30000
  server_failure_limit: 2
  timeout: 400
  preconnect: true
  servers:
   - 127.0.0.1:7003:1
```

It overwrites `- 127.0.0.1:7001:1` and - `127.0.0.1:7002:1` in the `servers:` section. I believe this is because of the way the nutcracker.yml configuration is written in code, versus using a template and filling in variables. See https://github.com/GluuFederation/cluster-mgr/blob/094212eb61af81b901a9ebe28c6a59f5e1abf98f/clustermgr/tasks/cache.py#L624.

We should create a template for nutcracker.yml that is populated based on all the servers in the database currently.
